language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - master
# cache this directory
cache:
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - openssl aes-256-cbc -K $encrypted_10b1d324a374_key -iv $encrypted_10b1d324a374_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli # 安装 hexo
install:
  - npm install # 安装 package.json 中的插件
script:
  - hexo clean
  - hexo generate
after_success:
  - git config --global user.name "meizijiu"
  - git config --global user.email "1197269596@qq.com"
  - hexo deploy
# E: Build LifeCycle
